<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Illuminate\Support\Facades\DB;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $permissions = [
            'utama-grup_pengguna-index',
            'utama-grup_pengguna-store',
            'utama-grup_pengguna-destroy',
            'utama-pengguna-index',
            'utama-pengguna-store',
            'utama-pengguna-destroy',            
            'utama-log_aplikasi-index',
            'utama-log_aplikasi-store',
            'utama-log_aplikasi-destroy',
            'data_master-referensi_sistem-index',
            'data_master-referensi_sistem-store',
            'data_master-referensi_sistem-destroy',
            'data_master-sumber_daya_manusia-index',
            'data_master-sumber_daya_manusia-store',
            'data_master-sumber_daya_manusia-destroy',
            'data_master-departemen-index',
            'data_master-departemen-store',
            'data_master-departemen-destroy',
            'data_master-profil_lembaga-index',
            'data_master-profil_lembaga-store',
            'data_master-profil_lembaga-destroy',
            'data_master-kamar-index',
            'data_master-kamar-store',
            'data_master-kamar-destroy',
            'data_master-referensi_akademik-index',
            'data_master-referensi_akademik_angkatan-store',
            'data_master-referensi_akademik_angkatan-destroy',
            'data_master-referensi_akademik_tingkat-store',
            'data_master-referensi_akademik_tingkat-destroy',
            'data_master-referensi_akademik_tahunajar-store',
            'data_master-referensi_akademik_tahunajar-destroy',
            'data_master-referensi_akademik_semester-store',
            'data_master-referensi_akademik_semester-destroy',
            'data_master-referensi_akademik_kelas-store',
            'data_master-referensi_akademik_kelas-destroy',
            'data_master-referensi_akademik_mutasi-store',
            'data_master-referensi_akademik_mutasi-destroy',
            'akademik-psb-index',
            'akademik-psb-store',
            'akademik-psb-destroy',
            'akademik-psb_kelompok_calon_santri-index',
            'akademik-psb_kelompok_calon_santri-store',
            'akademik-psb_kelompok_calon_santri-destroy',
            'akademik-psb_data_calon_santri-index',
            'akademik-psb_data_calon_santri-store',
            'akademik-psb_data_calon_santri-destroy',
            'akademik-psb_penempatan_santri_baru-index',
            'akademik-psb_penempatan_santri_baru-store',
            'akademik-psb_penempatan_santri_baru-destroy',
            'akademik-psb_konfigurasi-index',
            'akademik-psb_konfigurasi-store',
            'akademik-psb_konfigurasi-destroy',
            'akademik-psb_kolom_calon_siswa-index',
            'akademik-psb_kolom_calon_siswa-store',
            'akademik-psb_kolom_calon_siswa-destroy',
            'akademik-psb_kolom_pilihan_calon_siswa-store',
            'akademik-psb_kolom_pilihan_calon_siswa-destroy',
            'akademik-penempatan_kamar_santri-index',
            'akademik-penempatan_kamar_santri-store',
            'akademik-penempatan_kamar_santri-destroy',
            'akademik-referensi_pelajaran-index',
            'akademik-referensi_pelajaran_aspek_penilaian-store',
            'akademik-referensi_pelajaran_aspek_penilaian-destroy',
            'akademik-referensi_pelajaran_kelompok_pelajaran-store',
            'akademik-referensi_pelajaran_kelompok_pelajaran-destroy',
            'akademik-data_pelajaran-index',
            'akademik-data_pelajaran-store',
            'akademik-data_pelajaran-destroy',
            'akademik-rpp_pelajaran-index',
            'akademik-rpp_pelajaran-store',
            'akademik-rpp_pelajaran-destroy',
            'akademik-jenis_pengujian-index',
            'akademik-jenis_pengujian-store',
            'akademik-jenis_pengujian-destroy',
            'akademik-aturan_grading-index',
            'akademik-aturan_grading-store',
            'akademik-aturan_grading-destroy',
            'akademik-guru-index',
            'akademik-guru-store',
            'akademik-guru-destroy',
            'akademik-aturan_penilaian_rapor-index',
            'akademik-aturan_penilaian_rapor-store',
            'akademik-aturan_penilaian_rapor-destroy',
            'akademik-jam_belajar-index',
            'akademik-jam_belajar-store',
            'akademik-jam_belajar-destroy',
            'akademik-jadwal_guru-index',
            'akademik-jadwal_guru-store',
            'akademik-jadwal_guru-destroy',
            'akademik-rekapitulasi_jadwal_guru-index',
            'akademik-kalender_akademik-index',
            'akademik-kalender_akademik-store',
            'akademik-kalender_akademik-destroy',
            'akademik-kalender_akademik_aktivitas-store',
            'akademik-kalender_akademik_aktivitas-destroy',
            'akademik-data_santri-index',
            'akademik-data_santri-store',
            'akademik-data_santri-destroy',
            'akademik-presensi_harian-index',
            'akademik-presensi_harian-store',
            'akademik-presensi_harian-destroy',
            'akademik-presensi_pelajaran-index',
            'akademik-presensi_pelajaran-store',
            'akademik-presensi_pelajaran-destroy',
            'akademik-penilaian_pelajaran-index',
            'akademik-penilaian_pelajaran-store',
            'akademik-penilaian_pelajaran-destroy',
            'akademik-perhitungan_nilai_rapor-index',
            'akademik-perhitungan_nilai_rapor-store',
            'akademik-perhitungan_nilai_rapor-destroy',
            'akademik-komentar_rapor-index',
            'akademik-komentar_rapor-store',
            'akademik-komentar_rapor-destroy',
            'akademik-kenaikan_kelas-index',
            'akademik-kenaikan_kelas-store',
            'akademik-kenaikan_kelas-destroy',
            'akademik-tidak_naik_kelas-index',
            'akademik-tidak_naik_kelas-store',
            'akademik-tidak_naik_kelas-destroy',
            'akademik-pindah_departemen-index',
            'akademik-pindah_departemen-store',
            'akademik-pindah_departemen-destroy',
            'akademik-kelulusan_alumni-index',
            'akademik-kelulusan_alumni-store',
            'akademik-kelulusan_alumni-destroy',
            'akademik-mutasi_santri-index',
            'akademik-mutasi_santri-store',
            'akademik-mutasi_santri-destroy',
            'akademik-audit_perubahan_nilai-index',
            'akademik-kartu_setoran_santri-index',
            'akademik-kartu_setoran_santri-store',
            'akademik-kartu_setoran_santri-destroy',
            'keuangan-kode_akun_perkiraan-index',
            'keuangan-kode_akun_perkiraan-store',
            'keuangan-kode_akun_perkiraan-destroy',
            'keuangan-tahun_buku-index',
            'keuangan-tahun_buku-store',
            'keuangan-tahun_buku-destroy',
            'keuangan-tutup_buku-index',
            'keuangan-tutup_buku-store',
            'keuangan-jenis_penerimaan-index',
            'keuangan-jenis_penerimaan-store',
            'keuangan-jenis_penerimaan-destroy',
            'keuangan-besar_pembayaran-index',
            'keuangan-besar_pembayaran-store',
            'keuangan-transaksi_penerimaan-index',
            'keuangan-transaksi_penerimaan-store',
            'keuangan-transaksi_pengeluaran-index',
            'keuangan-transaksi_pengeluaran-store',
            'keuangan-jenis_tabungan_santri-index',
            'keuangan-jenis_tabungan_santri-store',
            'keuangan-jenis_tabungan_santri-destroy',
            'keuangan-transaksi_tabungan_santri-index',
            'keuangan-transaksi_tabungan_santri-store',
            'keuangan-jenis_tabungan_pegawai-index',
            'keuangan-jenis_tabungan_pegawai-store',
            'keuangan-jenis_tabungan_pegawai-destroy',
            'keuangan-transaksi_tabungan_pegawai-index',
            'keuangan-transaksi_tabungan_pegawai-store',
            'keuangan-transaksi_jurnal_umum-index',
            'keuangan-transaksi_jurnal_umum-store',
        ];
 
        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission]);
        }

        // initial admin roles
        if (DB::table('public.role_has_permissions')->count() < 1)
        {
            $permissions = Permission::select('id')->get();
            foreach ($permissions as $permission) 
            {
                DB::table('public.role_has_permissions')->insertOrIgnore([
                    [ 'permission_id' => $permission->id, 'role_id' => 1 ],
                ]);
            }
        }
    }
}
